version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'student_management_system'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
    expose:
    - '3306'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    container_name: student_management_system_backend
    volumes:
      - .:/student_management_system_backend
    ports:
      - "9000:9000"
    depends_on:
      - db