# Generated by Django 2.0.13 on 2020-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('major', models.CharField(max_length=30)),
            ],
        ),
    ]
